FROM openjdk:17.0.1-slim
COPY ./cacerts /etc/ssl/certs/java/
ARG VERSION
ENV JAR_VERSION=$VERSION
COPY target/security-portal-authz-$VERSION.jar /usr/app/wily-start-project.jar
ENTRYPOINT ["java","-Duser.timezone=GMT","-jar","/usr/app/wily-start-project.jar"]
